version: "3"

services:
  todo:
    build:
      context: .
    container_name: todo
    image: todo:latest
    ports:
      - 7777:8080
    depends_on:
      - mysql
    networks:
      - todo-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/lesson
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_FLYWAY_URL=jdbc:mysql://mysql:3306
      - SPRING_PROFILES_ACTIVE=form

  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=todo
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3310:3306
    networks:
      - todo-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

networks:
  todo-network:

volumes:
  database: